---
- name: Manage users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    state: "{{ item.state }}"
    groups: "{{ item.groups | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    update_password: on_create
  loop: "{{ users }}"
  when: item.state != 'absent'

- name: Delete users
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: absent
  loop: "{{ users }}"
  when: item.state == 'absent'
