---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install required utilities
  ansible.builtin.apt:
    name: "{{ system_utils_packages }}"
    state: present
  when: ansible_os_family == "Debian"

