version: "3.8"
services:
  ansible_test:
    build: .
    image: ansible_test_image
    ports:
      - "2223:22"
    networks:
      - default
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
    restart: always

networks:
  default:
    driver: bridge
