- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Configure nginx
  ansible.builtin.template:
    src: vhost.j2
    dest: /etc/nginx/sites-available/default

- name: Enable nginx configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
